//! `cargo test` gate for the builder fixtures.
//!
//! The corpus tests in `generated.rs` are code-generated by `build.rs` because their inputs are
//! files on disk. The builder fixtures are already a Rust `Vec`, so no codegen is needed — and a
//! single test that runs every fixture before panicking reports the whole picture in one run,
//! rather than stopping at whichever fixture happens to sort first.

use openscenario_roundtrip_harness::{builder_fixtures, check_builder_fixture, load_schema};

#[test]
fn builder_fixtures_roundtrip_and_validate() {
    let mut validator = load_schema().expect("load Schema/OpenSCENARIO.xsd");

    let mut report = String::new();
    let mut failed = 0usize;

    let fixtures = builder_fixtures::fixtures();
    for fixture in &fixtures {
        for failure in check_builder_fixture(fixture, &mut validator) {
            failed += 1;
            report.push_str(&format!("\n{}: {}\n", fixture.name, failure));
        }
    }

    assert!(
        failed == 0,
        "{failed} builder check(s) failed across {} fixtures:{report}",
        fixtures.len()
    );
}
